language: node_js
node_js:
  - "10"
before_install:
  - export TZ=Africa/Nairobi
  - date
services:
  - xvfb
install:
  - npm install
script:
  - npm run lint
  - npm run test:coverage
  - npm run build:lib
addons:
  apt:
    packages:
    - google-chrome-stable
