language: node_js
node_js:
  - '8'
before_install:
  - export TZ=Africa/Nairobi
  - date
services:
  - xvfb
install:
  - npm install
script:
  - npm run build:lib
  - npm run test
addons:
  apt:
    packages:
      - google-chrome-stable
